### ISSUE TITLE
Diamond operator refactoring generates code that does not compile

### ISSUE THREAD

**Issue by gboismal** [JnRouvignac/AutoRefactor#121]
## Given
following code:
```java
Collection<String> myCollection = ...; 
List<Object> newElements = new ArrayList<Object>(myCollection);
```
# When

...automated refactorings are applied...
# Then
Generated code does not compile:
```java
List<Object> newElements = new ArrayList<>(myCollection);
```

**Comment by JnRouvignac** [comment]
I have been investigating this one for a long time, and I have not found how to fix it.
I have been trying to identify that in the `ArrayList<Object>` expression, `Object` is the generic type parameter of the `ArrayList` type, rather than the generic type parameter of a method/constructor. However, I cannot seem to get this information from JDT, thus I cannot infer that it is not safe to remove the `Object` generic type parameter.
Fixing this bug is on hold for the moment.
