### ISSUE TITLE
Contributing to Autorefactor

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#151]
Hi,

Autorefactor looks like the tool I wanted to write myself for the last 10 years as it feals but never got to.
Thank you for actually writing it and giving us access to your hard work.
I tried it on a file and noticed that some comments got lost or are modified in a wrong way.
Looking at the refactorings code some reasons are obvious and open issue tickets show awareness.
I want to tackle some of those but have problems to get eclipse setup properly for hacking the code.
I am an experienced java developer with compiler background and  I am using git/svn/ant/ivy/gradle/intellij idea routinely.
I can use maven and eclipse for basic stuff.
But I failed to get an eclipse setup that contains ALL needed dependencies  including SOURCE and JAVADOC.
Throw tycho into the mix and I got lost.
Can someone provide a short list of the steps what to do to get a workspace containing AutoRefactor project including ALL needed dependencies  including SOURCE and JAVADOC starting with some vanilla eclipse mars J2EE?

The major points that come to my mind:
- Which plugins to install?
- Which maven commands to issue for the major tasks to be done?
- How to integrate sources/javadoc in THIS case? (There must be some better way then downloading and adding to .classpath?)
- How to import into eclipse?

Thanks in advance!

Cal

**Comment by JnRouvignac** [comment]
Hello,

Thanks for coming back to me. This is great feedback!
The project generally needs more documentation to help potential contributors.

I have created [Hacking AutoRefactor](https://github.com/JnRouvignac/AutoRefactor/wiki/Hacking-AutoRefactor) and updated [CONTRIBUTING.md](https://github.com/JnRouvignac/AutoRefactor/blob/master/CONTRIBUTING.md) to help you out.

I think I have covered everything, but please let me know if you are missing anything.
Also please close this issue once you are satisfied your problem is fixed.
Finally you may use gitter to discuss any problems you have. I will send you an invite.

Happy hacking!

**Comment by cal101** [comment]
Hey,

looks cool. Totally different from my wild guessing. Will give it a try ASAP.

Cal

**Comment by cal101** [comment]
Hey,

looks much better.
I had to do a fresh git checkout to resolve junit bundle dependency.
The TestNGAssert tests fails for whatever reason in IDE and command line. 

Is it OK to run eclipse with java 8 or should java 7 be used?

JRE system Library was automatically set to 1.6, is that OK?
How can I get source and javadoc into IDE for org.eclipse.jdt.core dependency?

Thanks for your help!

Cal

**Comment by JnRouvignac** [comment]
Hello Cal,

> I had to do a fresh git checkout to resolve junit bundle dependency.

I think a git pull may have sorted it.
I had to update the code to make this procedure work.

> The TestNGAssert tests fails for whatever reason in IDE and command line.

I had to setup the unit test's `ASTParser` to add the testng jar to its classpath. It knows it has to add it because it is specified in the pom.xml of the "plugin.tests" project.
See `plugin.tests/src/test/java/org/autorefactor/refactoring/rules/JavaCoreHelper.getM2Repository()`.
You should be able to debug this from Eclipse

> Is it OK to run eclipse with java 8 or should java 7 be used?

I am using java 7, but I assume it should work.

> JRE system Library was automatically set to 1.6, is that OK?

I think so.

> How can I get source and javadoc into IDE for org.eclipse.jdt.core dependency?

I have added a section detailing how to install "Eclipse JDT Plug-in Developer Resources" in [Hacking AutoRefactor](https://github.com/JnRouvignac/AutoRefactor/wiki/Hacking-AutoRefactor).
Let me know if this is what you are looking for.

&nbsp;

Thanks for taking the time to try it all out and hack on AutoRefactor!!

**Comment by cal101** [comment]
Just a short note because I have to leave now.
Making somewhat progress in hacking. (I didn't try source code include yet.)

```
        // keep this comment 2
                    
        // keep this comment 1
        if (b1 && (b2 || b3)) {
```
Not exactly what was asked for but ... ;-)

**Comment by JnRouvignac** [comment]
Great!
Getting there!

**Comment by cal101** [comment]
Moin!

Source code of plugins work. Good descriptions. 

In ASTCommentRewriter you are adding "\r\n". That breaks us linux guys.
I guess what you want is 

final CompilationUnit cu = (CompilationUnit) outerIf.getRoot(); 
String lineSep = cu.getTypeRoot().findRecommendedLineSeparator();

Learned that a few minutes ago ;-)

Is there some communication channel for exchanging solutions and discussing stuff?

My first test cases work. Brute force just getting through. Not nearly ready for inclusion.

Cal

**Comment by JnRouvignac** [comment]
Hi Cal,

You're welcome, thanks for pushing on your side :)

Thanks for the feedback on `ASTCommentRewriter`, I think that when I wrote it, I was so damn busy getting it right that I stuck "\r\n" and forgot to revisit it later.
I am a bit surprised when you write that it breaks you. I am using Linux and did not see any issue with it.
I will fix it anyway.

We can chat on [gitter](https://gitter.im/JnRouvignac/AutoRefactor?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge) if you want to discuss things further. There public rooms and private discussions are also possible.

I think you have all your questions answered in the current issue, so I am closing it now.

Thanks!
