### ISSUE TITLE
[patch] Annoying remaining loop variable occurrence

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [JnRouvignac/AutoRefactor#201]
When
```
Map<String, List<String>> mapToFill = new HashMap<>();
List<String> inputList = new ArrayList<>();
for (String input : inputList) {
    mapToFill.get(input).add(input);
}
```

Then
```
Map<String, List<String>> mapToFill = new HashMap<>();
List<String> inputList = new ArrayList<>();
mapToFill.get(input).addAll(inputList);
```

(compilation error)

The problem is that we remove a variable but an occurrence may remain. So we should first count the number of occurrences of `input` and if there is only one occurrence, we can refactor.

Here is the patch with the tests:
[AnnoyingLoopVariableOccurrence.txt](https://github.com/JnRouvignac/AutoRefactor/files/407682/AnnoyingLoopVariableOccurrence.txt)

**Comment by JnRouvignac** [comment]
Thanks a lot for another bug report and patch at the same time!

I am going too merge it, but I am changing a few things:
* `VariableOccurenceCounterVisitor` => `VariableUseCounterVisitor` (to match traditional compiler lingo, for example: [Use-Definition Chain](https://en.wikipedia.org/wiki/Use-define_chain))
    * I also changed method and field names in this method
* I extracted `getVariableUseCount()` method
* I added a null check on the resolved variable binding to avoid uselessly calling the `VariableUseCounterVisitor` because the variable use count would always be 0 in such case
* I added copyright attributions to you
