### ISSUE TITLE
[patch] New refactoring - Switch refactoring

### ISSUE THREAD

**Issue by Fabrice-TIERCELIN** [JnRouvignac/AutoRefactor#202]
Here is a patch for the switch refactoring. It uses a switch statement when possible. This first version only deals with primitive types and literals.
[Switch.txt](https://github.com/JnRouvignac/AutoRefactor/files/431737/Switch.txt)

**Comment by JnRouvignac** [comment]
Hi Fabrice,

Thanks a lot for the quality contribution you just made!
Complete code and test cases. This is very impressive!

This time I committed your patch as is.
I then elected to do further changes as separate commits.
I have tried to separate them were it made sense particularly to highlight different concerns.

One commit (c84a36eb509810a97200f4acd3bafada594a566d) looks big, and may be hard to read, but it is only refactoring.
It focuses on readability by using shorter names, expressiveness by using dedicated types (instead of `Pair`), consistency with the rest of the code and safer constructs.
Please let me know if you have any concerns over the changes I did.

Thanks again for this great and clean contribution!
