### ISSUE TITLE
Static class name elimination buggy

### ISSUE THREAD

**Issue by gzsombor** [JnRouvignac/AutoRefactor#222]
Try the following code : 

```java
class StaticError {
    static String property = null;
    static void setProperty(String property) {
        StaticError.property = property;
    }
}
class Other {
    void foo() {
        StaticError.setProperty("hi");
    }
}
```

This will be refactored to:

```java
class StaticError {
    static String property = null;

    static void setProperty(String property) {
        property = property;
    }
}

class Other {
    void foo() {
        setProperty("hi");
    }
}
```

Which is wrong, first the setter does not do anything, second, the static method is not accessible from the Other class.

**Comment by JnRouvignac** [comment]
Thanks @gzsombor for this report.

I noticed the same problem when running this rule on a big codebase.
I have not had time to fix it yet.

This bug is due to bad handling of name shadowing.
I think there may be a bit more examples beyond what you reported which will fail.

Hopefully, I'll get to fix this after closing the currently opened PRs.

**Comment by Fabrice-TIERCELIN** [comment]
@gzsombor, can you please tell me if my PR #241 entirely fix this issue?

**Comment by gzsombor** [comment]
It seems, that the first part is fixed by your commit, but not the 

```
class Other {
    void foo() {
        StaticError.setProperty("hi");
    }
}

```

**Comment by Fabrice-TIERCELIN** [comment]
Can I have the entire .java file(s) with the packages, imports and so on to study the case, @gzsombor?

**Comment by gzsombor** [comment]
Sure, just check my pull request about the error
