### ISSUE TITLE
RemoveUnnecessaryLocalBeforeReturnRefactoring and RemoveUnnecessaryCastRefactoring together

### ISSUE THREAD

**Issue by gzsombor** [JnRouvignac/AutoRefactor#243]
could cause serious problems:

```
    InnerService service;

    public String doNotEliminateEverything(String param) {
        param = (String) service.transform(param);
        return param;
    }

    public Object otherMethodCall(String param) {
        param = service.transform(param);
        return param;
    }

    static class InnerService {
        public String transform(String a) {
            return a + a;
        }
    }
```

converted to this:

```
    InnerService service;
    
    public String doNotEliminateEverything(String param) {
        return (String) ;
    }

    public Object otherMethodCall(String param) {
        return service.transform(param);
    }

    static class InnerService {
        public String transform(String a) {
            return a + a;
        }
    }
```

It seems, that the RemoveUnnecessaryLocalBeforeReturnRefactoring#replaceReturnStatement still tries to replace the 'CastExpression', which was previously eliminated by RemoveUnnecessaryCastRefactoring.
 How this supposed to be work? I guess, it would be better, if all the AST changes would be applied to the tree, and only then, a new rule could be executed. Of course, it's need to be tracked, if any change is made during a rule execution, then all the previously rules should be re-tried again. Or is there any other way to fix this?

**Comment by JnRouvignac** [comment]
This is unfortunate.
Since building the AST from source is a costly operation, AutoRefactor first builds the AST and reuse as much as possible that same AST. So it runs multiple rules on the same AST.

There are mechanisms in place to remove such problems (`ASTHelper.DO_NOT_VISIT_SUBTREE`, `AbstractRefactoringRule.preVisit2()`) but these are not perfect. For example when previous sibling nodes to the visited node are being refactored. See the call hierarchy for `Refactorings.hasBeenRefactored()`.
I am still to find a better way to avoid this.

The obvious alternative would be to not share AST's per rule, but the performance cost is high.

**Comment by gzsombor** [comment]
Understandable, the concerns for performance, but currently we are trying to execute two refactor parallely which leads to this inconsistencies. 
 AST could be shared between rules, until one rule has modified something, in that case, the modifications should be applied, and a new AST construction is needed. Yes, this huge one-visitor-to-call-them-all class makes this change a bit harder. 
 But without separating securely the refactoring tasks, I think, there will be always tricky cases where two rule collide

**Comment by Fabrice-TIERCELIN** [comment]
I think I have found a solution. Instead of visiting one of the two statements, we visit the method body containing the statements and we use a second visitor. If the second visitor has refactored something, we return `ASTHelper.DO_NOT_VISIT_SUBTREE` for the whole method body.

I think this approach should be adopted each time we refactor a previous sibling or a next sibling.
