### ISSUE TITLE
BigNumberCleanUp - code not compilable because of wrong refactoring

### ISSUE THREAD

**Issue by cal101** [JnRouvignac/AutoRefactor#450]
Do not change

```
BigInteger MAX_63_BIT_UNSIGNED_VALUE_AS_BIG_INTEGER = new BigInteger("9223372036854775808");
```

to

```
BigInteger MAX_63_BIT_UNSIGNED_VALUE_AS_BIG_INTEGER = BigInteger.valueOf(9223372036854775808);
```

**Comment by Fabrice-TIERCELIN** [comment]
This bug is simple to fix. The problem is that the BigNumberCleanUp rule itself is hard to understand. It has been coded by @JnRouvignac and I can't figure out why we do such things. I understand the part that makes use of constants. But the remaining part of the cleanup is weird.

So either:

1. You can explain me the interest of the actions and I will fix the bug following this interest
1. I will simply remove those actions.

**Comment by cal101** [comment]
The refactoring does indeed a number of strange things.
I think it deals with
https://rules.sonarsource.com/java/RSPEC-2111
and using the availabe constants is ok, too.
Maybe it's simpler to rewrite from scratch.
